version: '3.8'

services:
  diabetes-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./app/models/saved_models:/app/app/models/saved_models
    restart: unless-stopped
    
  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - diabetes-api
    restart: unless-stopped
